version: '3.8'

services:
    loma-api:
        image: loma-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        environment: 
            TZ: Asia/Bangkok
        ports:
            - 5010:5010
            # - 9229:9229
        networks:
            - loma-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on: 
            - loma_db
    loma_db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - loma-network
        environment:
            MYSQL_ROOT_PASSWORD: loma
            MYSQL_DATABASE: loma

    loma_db_admin:
        image: phpmyadmin
        restart: always
        networks:
            - loma-network
        environment:
            PMA_HOST: loma_db
        ports:
        - "8080:80"
        depends_on: 
            - loma_db
    redis:
        image: "redis:alpine"
        hostname: redis
        # ports:
        # - "6379:6379"
        networks:
            - loma-network

networks:
    loma-network: